/**
 * modaic/backend/src/services/trends.service.js
 * Weekly AI trend alerts — personalized per user based on their wardrobe
 * Generated by cron job, stored in DB, served instantly to frontend
 */

const WardrobeItem = require('../models/WardrobeItem.model');
const User = require('../models/User.model');
const TrendAlert = require('../models/TrendAlert.model');
const { getModel, getModelName } = require('../config/gemini');
const logger = require('../config/logger');

/**
 * Generate trend alert for a single user
 */
const generateTrendAlertForUser = async (userId) => {
  const client = getModel();
  if (!client) return null;

  try {
    const [items, user] = await Promise.all([
      WardrobeItem.find({ userId, isActive: true }).select('name category colors pattern aiTags'),
      User.findById(userId).select('name styleProfile styleEmbedding'),
    ]);

    if (items.length < 2) return null;

    // Build wardrobe summary
    const patternCounts = {};
    const colorCounts  = {};
    const catCounts    = {};
    items.forEach(item => {
      if (item.pattern) patternCounts[item.pattern] = (patternCounts[item.pattern] || 0) + 1;
      item.colors?.forEach(c => { colorCounts[c] = (colorCounts[c] || 0) + 1; });
      catCounts[item.category] = (catCounts[item.category] || 0) + 1;
    });

    const topPattern = Object.entries(patternCounts).sort((a, b) => b[1] - a[1])[0];
    const topColor   = Object.entries(colorCounts).sort((a, b) => b[1] - a[1])[0];
    const topCat     = Object.entries(catCounts).sort((a, b) => b[1] - a[1])[0];

    const result = await client.chat.completions.create({
      model: getModelName(),
      messages: [
        {
          role: 'system',
          content: `You are Luna, an AI fashion stylist for Modaic. You write personalized weekly trend alerts for users based on their actual wardrobe. Be warm, specific, and actionable. Use light emoji 🌸✨.`,
        },
        {
          role: 'user',
          content: `Generate a weekly trend alert for ${user.name}.

Their wardrobe highlights:
- Most common category: ${topCat?.[0] || 'tops'} (${topCat?.[1] || 0} items)
- Most common color: ${topColor?.[0] || 'neutral'} (${topColor?.[1] || 0} items)
- Most common pattern: ${topPattern?.[0] || 'solid'} (${topPattern?.[1] || 0} items)
- Total items: ${items.length}
- Style: ${user.styleProfile?.primaryStyle || 'casual'}

Write a trend alert with:
1. A catchy title (max 8 words)
2. 2-3 sentences about what's trending that matches THEIR wardrobe
3. Exactly 3 specific outfit tips using what they own
4. One item they should consider adding

Return ONLY valid JSON:
{
  "title": "Your Trend Alert Title",
  "summary": "2-3 sentence trend summary referencing their wardrobe",
  "tips": ["tip 1", "tip 2", "tip 3"],
  "suggestion": "one item to consider adding",
  "badge": "🌸 or ✨ or 👗 or 💫 (pick one emoji)"
}`,
        },
      ],
      temperature: 0.9,
      max_tokens: 600,
    });

    const text = result.choices[0].message.content.trim();
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return null;

    const trendData = JSON.parse(jsonMatch[0]);

    // Upsert trend alert for this user (one active alert per user)
    const alert = await TrendAlert.findOneAndUpdate(
      { userId },
      {
        userId,
        ...trendData,
        generatedAt: new Date(),
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
      },
      { upsert: true, new: true }
    );

    logger.info(`Trend alert generated for user ${userId}`);
    return alert;
  } catch (err) {
    logger.error(`Trend generation error for ${userId}: ${err.message}`);
    return null;
  }
};

/**
 * Run for ALL users — called by cron job daily
 * Processes users in batches to avoid rate limits
 */
const generateTrendAlertsForAllUsers = async () => {
  logger.info('🌸 Starting weekly trend alert generation...');
  const users = await User.find({ isActive: true }).select('_id').lean();
  let success = 0;

  for (const user of users) {
    await generateTrendAlertForUser(user._id);
    success++;
    // Small delay between users to respect rate limits
    await new Promise(r => setTimeout(r, 2000));
  }

  logger.info(`✦ Trend alerts generated for ${success}/${users.length} users`);
  return { success, total: users.length };
};

/**
 * Get current trend alert for a user
 */
const getUserTrendAlert = async (userId) => {
  const alert = await TrendAlert.findOne({
    userId,
    expiresAt: { $gt: new Date() },
  });
  return alert;
};

module.exports = {
  generateTrendAlertForUser,
  generateTrendAlertsForAllUsers,
  getUserTrendAlert,
};